//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseHandler
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoiceheader
    {
        public int invoiceno { get; set; }
        public string invoicedate { get; set; }
        public decimal totaldiscount { get; set; }
        public decimal totalprice { get; set; }
    }
}
