//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseHandler
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginDetail
    {
        public int User_Id { get; set; }
        public string Full_Name { get; set; }
        public string Address { get; set; }
        public string Nic_No { get; set; }
        public string Telephone_No { get; set; }
        public string Gender { get; set; }
        public string User_Name { get; set; }
        public string Password { get; set; }
    }
}
