//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseHandler
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentDetail
    {
        public int Payment_Id { get; set; }
        public decimal Drawer_Amount { get; set; }
        public Nullable<decimal> WithDrawer_Amount { get; set; }
        public string Date { get; set; }
    }
}
