//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseHandler
{
    using System;
    using System.Collections.Generic;
    
    public partial class product1
    {
        public string productid { get; set; }
        public string barcode { get; set; }
        public string description { get; set; }
        public decimal quantity { get; set; }
        public string expiredate { get; set; }
        public decimal sellingprice { get; set; }
        public decimal purchaseprice { get; set; }
        public Nullable<decimal> discountprice { get; set; }
        public Nullable<int> discountquantity { get; set; }
    }
}
